# =========================
# BUILD STAGE
# =========================
FROM node:22-alpine AS builder

WORKDIR /app

# Copiar solo package primero (mejor cache)
COPY package*.json ./

# Instalar todas las dependencias 
RUN npm ci

# Copiar código
COPY . .

# Compilar TypeScript
RUN npm run build


# =========================
# PRODUCTION STAGE :)
# =========================
FROM node:22-alpine AS production

WORKDIR /app

ENV NODE_ENV=production

# Copiar solo package
COPY package*.json ./

# Instalar solo prod deps
RUN npm ci --omit=dev

# Copiar build desde builder
COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/main.js"]