# sonar.projectKey=jac2206_chasis-express-ts
# sonar.organization=jac2206
# sonar.sources=src
# sonar.tests=test
# sonar.typescript.lcov.reportPaths=coverage/lcov.info
# sonar.sourceEncoding=UTF-8
# sonar.coverage.exclusions=src/main.ts,src/server.ts,src/domain/interfaces/**,src/infraestructure/routes/**, src/infraestructure/logger/**